ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

-- 계정 생성
CREATE USER final_ver1 IDENTIFIED BY "project1234";

-- 권한 부여
GRANT CONNECT, RESOURCE, CREATE VIEW TO final_ver1;

-- 객체 생성 공간 할당
ALTER USER final_ver1 DEFAULT TABLESPACE SYSTEM
QUOTA UNLIMITED ON SYSTEM;

--------------------------------------------------------------------------------

DROP TABLE "MEMBER";

CREATE TABLE "MEMBER" (
   "MEMBER_NO"   NUMBER      NOT NULL,
   "MEMBER_EMAIL"   VARCHAR2(50)      NULL,
   "MEMBER_PW"   VARCHAR2(50)      NULL,
   "MEMBER_NAME"   VARCHAR2(20)      NULL,
   "MEMBER_NICKNAME"   VARCHAR2(30)      NULL,
   "MEMBER_TEL"   VARCHAR2(30)      NULL,
   "MEMBER_ADDRESS"   VARCHAR2(100)      NULL,
   "SECESSION_FL"   CHAR   DEFAULT 'N'   NULL,
   "AUTHORITY"   NUMBER   DEFAULT 2   NULL,
   "PROFILE"   VARCHAR2(200)      NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '이메일(아이디)';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '비밀번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_NAME" IS '이름';

COMMENT ON COLUMN "MEMBER"."MEMBER_NICKNAME" IS '닉네임';

COMMENT ON COLUMN "MEMBER"."MEMBER_TEL" IS '전화번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_ADDRESS" IS '주소';

COMMENT ON COLUMN "MEMBER"."SECESSION_FL" IS '탈퇴 Y';

COMMENT ON COLUMN "MEMBER"."AUTHORITY" IS '관리자 1';

COMMENT ON COLUMN "MEMBER"."PROFILE" IS '프로필 이미지';




DROP TABLE "MEMBER";

CREATE TABLE "MEMBER" (
   "MEMBER_NO"   NUMBER      NOT NULL,
   "MEMBER_EMAIL"   VARCHAR2(50)      NULL,
   "MEMBER_PW"   VARCHAR2(50)      NULL,
   "MEMBER_NAME"   VARCHAR2(20)      NULL,
   "MEMBER_NICKNAME"   VARCHAR2(30)      NULL,
   "MEMBER_TEL"   VARCHAR2(30)      NULL,
   "MEMBER_ADDRESS"   VARCHAR2(100)      NULL,
   "SECESSION_FL"   CHAR   DEFAULT 'N'   NULL,
   "AUTHORITY"   NUMBER   DEFAULT 2   NULL,
   "PROFILE"   VARCHAR2(200)      NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '이메일(아이디)';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '비밀번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_NAME" IS '이름';

COMMENT ON COLUMN "MEMBER"."MEMBER_NICKNAME" IS '닉네임';

COMMENT ON COLUMN "MEMBER"."MEMBER_TEL" IS '전화번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_ADDRESS" IS '주소';

COMMENT ON COLUMN "MEMBER"."SECESSION_FL" IS '탈퇴 Y';

COMMENT ON COLUMN "MEMBER"."AUTHORITY" IS '관리자 1';

COMMENT ON COLUMN "MEMBER"."PROFILE" IS '프로필 이미지';

DROP TABLE "SUBSCRIBE";

CREATE TABLE "SUBSCRIBE" (
   "SUBSCRIBE_NO"   NUMBER      NOT NULL,
   "SUBSCRIBE_START"   VARCHAR2(100)      NULL,
   "SUBSCRIBE_END"   VARCHAR2(100)      NULL,
   "SUBSCRIBE_LEVEL"   NUMBER      NULL,
   "MEMBER_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "SUBSCRIBE"."SUBSCRIBE_NO" IS '구독번호';

COMMENT ON COLUMN "SUBSCRIBE"."SUBSCRIBE_START" IS '구독시작일';

COMMENT ON COLUMN "SUBSCRIBE"."SUBSCRIBE_END" IS '구독 종료일';

COMMENT ON COLUMN "SUBSCRIBE"."SUBSCRIBE_LEVEL" IS '한 달 = 1';

COMMENT ON COLUMN "SUBSCRIBE"."MEMBER_NO" IS '회원번호';

DROP TABLE "CALCULATE";

CREATE TABLE "CALCULATE" (
   "CALCULATE_NO"   NUMBER      NOT NULL,
   "CALCULATE_WAY"   NUMBER      NULL,
   "CALCULATE_FL"   NUMBER      NULL,
   "PRICE"   VARCHAR2(100)      NULL,
   "SUBSCRIBE_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "CALCULATE"."CALCULATE_NO" IS '결제번호';

COMMENT ON COLUMN "CALCULATE"."CALCULATE_WAY" IS '무통장=1/카드=2';

COMMENT ON COLUMN "CALCULATE"."CALCULATE_FL" IS '결제X = 1 / O=2';

COMMENT ON COLUMN "CALCULATE"."PRICE" IS '결제 금액';

COMMENT ON COLUMN "CALCULATE"."SUBSCRIBE_NO" IS '구독번호';

DROP TABLE "BOARD";

CREATE TABLE "BOARD" (
   "BOARD_NO"   NUMBER      NOT NULL,
   "BOARD_TITLE"   VARCHAR2(100)      NULL,
   "BOARD_CONTENT"   VARCHAR2(3000)      NULL,
   "BOARD_DT"   DATE   DEFAULT SYSDATE   NULL,
   "BOARD_UPDATE_DT"   DATE   DEFAULT SYSDATE   NULL,
   "BOARD_ST"   CHAR   DEFAULT 'N'   NULL,
   "READ_COUNT"   NUMBER   DEFAULT 0   NULL,
   "BOARD_CODE"   NUMBER      NOT NULL,
   "MEMBER_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '게시글 번호';

COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '게시글 제목';

COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '게시글 내용';

COMMENT ON COLUMN "BOARD"."BOARD_DT" IS '작성일';

COMMENT ON COLUMN "BOARD"."BOARD_UPDATE_DT" IS '수정일';

COMMENT ON COLUMN "BOARD"."BOARD_ST" IS '삭제 Y';

COMMENT ON COLUMN "BOARD"."READ_COUNT" IS '조회수';

COMMENT ON COLUMN "BOARD"."BOARD_CODE" IS '게시판 코드';

COMMENT ON COLUMN "BOARD"."MEMBER_NO" IS '회원번호';

DROP TABLE "BOARD_TYPE";

CREATE TABLE "BOARD_TYPE" (
   "BOARD_CODE"   NUMBER      NOT NULL,
   "BOARD_NAME"   VARCHAR2(100)      NULL
);

COMMENT ON COLUMN "BOARD_TYPE"."BOARD_CODE" IS '게시판 코드';

COMMENT ON COLUMN "BOARD_TYPE"."BOARD_NAME" IS '게시판 이름';

DROP TABLE "COMMENT";

CREATE TABLE "COMMENT" (
   "COMMENT_NO"   NUMBER      NOT NULL,
   "COMMENT_CONTENT"   VARCHAR2(1000)      NULL,
   "COMMENT_DT"   DATE   DEFAULT SYSDATE   NULL,
   "COMMENT_ST"   CHAR   DEFAULT 'N'   NULL,
   "MEMBER_NO"   NUMBER      NOT NULL,
   "BOARD_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "COMMENT"."COMMENT_NO" IS '댓글 번호';

COMMENT ON COLUMN "COMMENT"."COMMENT_CONTENT" IS '댓글 내용';

COMMENT ON COLUMN "COMMENT"."COMMENT_DT" IS '댓글 작성일';

COMMENT ON COLUMN "COMMENT"."COMMENT_ST" IS '삭제 Y';

COMMENT ON COLUMN "COMMENT"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "COMMENT"."BOARD_NO" IS '게시글 번호';

DROP TABLE "EVENT_CALENDAR";

CREATE TABLE "EVENT_CALENDAR" (
   "MEMBER_NO"   NUMBER      NOT NULL,
   "CALENDAR_DT"   VARCHAR2(100)   DEFAULT SYSDATE   NULL
);

COMMENT ON COLUMN "EVENT_CALENDAR"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "EVENT_CALENDAR"."CALENDAR_DT" IS '출석체크 날짜';

DROP TABLE "CHATTING_ROOM";

CREATE TABLE "CHATTING_ROOM" (
   "CHATTING_NO"   NUMBER      NOT NULL,
   "OPEN_MEMBER"   NUMBER      NOT NULL,
   "PARTICIPANT"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "CHATTING_ROOM"."CHATTING_NO" IS '채팅방 번호';

COMMENT ON COLUMN "CHATTING_ROOM"."OPEN_MEMBER" IS '개설자 회원번호';

COMMENT ON COLUMN "CHATTING_ROOM"."PARTICIPANT" IS '참여자 회원번호';

DROP TABLE "MESSAGE";

CREATE TABLE "MESSAGE" (
   "MESSAG_NO"   NUMBER      NOT NULL,
   "MESSAGE_CONTENT"   VARCHAR2(1000)      NULL,
   "READ_FL"   CHAR   DEFAULT 'N'   NULL,
   "SEND_TIME"   DATE   DEFAULT SYSDATE   NULL,
   "CHATTING_NO"   NUMBER      NOT NULL,
   "SENDER_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "MESSAGE"."MESSAG_NO" IS '메세지 번호';

COMMENT ON COLUMN "MESSAGE"."MESSAGE_CONTENT" IS '메세지 내용';

COMMENT ON COLUMN "MESSAGE"."READ_FL" IS '읽음 Y';

COMMENT ON COLUMN "MESSAGE"."SEND_TIME" IS '보낸 시간';

COMMENT ON COLUMN "MESSAGE"."CHATTING_NO" IS '채팅방 번호';

COMMENT ON COLUMN "MESSAGE"."SENDER_NO" IS '보낸 회원 번호';

DROP TABLE "REPORT";

CREATE TABLE "REPORT" (
   "REPORT_NO"   NUMBER      NOT NULL,
   "REPORTED_NO"   NUMBER      NOT NULL,
   "REPORT_CONTENT"   VARCHAR2(1000)      NULL,
   "BC_NO"   NUMBER      NOT NULL,
   "REPORT_CODE"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "REPORT"."REPORT_NO" IS '신고한 사람';

COMMENT ON COLUMN "REPORT"."REPORTED_NO" IS '신고당한 사람';

COMMENT ON COLUMN "REPORT"."REPORT_CONTENT" IS '신고내용';

COMMENT ON COLUMN "REPORT"."BC_NO" IS '게시글 채팅방 번호';

COMMENT ON COLUMN "REPORT"."REPORT_CODE" IS '신고 분류 코드';

DROP TABLE "TARGET";

CREATE TABLE "TARGET" (
   "TARGET_MN"   NUMBER      NULL,
   "MEMBER_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "TARGET"."TARGET_MN" IS '목표예산';

COMMENT ON COLUMN "TARGET"."MEMBER_NO" IS '회원번호';

DROP TABLE "MILEAGE";

CREATE TABLE "MILEAGE" (
   "MEMBER_NO"   NUMBER      NOT NULL,
   "MILEAGE"   NUMBER      NULL
);

COMMENT ON COLUMN "MILEAGE"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "MILEAGE"."MILEAGE" IS '보유마일리지';

DROP TABLE "CONTEST";

CREATE TABLE "CONTEST" (
   "MEMBER_NO"   NUMBER      NOT NULL,
   "TEST_TITLE"   VARCHAR2(100)      NULL,
   "TEST_CONTENT"   VARCHAR2(1000)      NULL
);

COMMENT ON COLUMN "CONTEST"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "CONTEST"."TEST_TITLE" IS '테스트제목';

COMMENT ON COLUMN "CONTEST"."TEST_CONTENT" IS '테스트내용';

DROP TABLE "LIKE";

CREATE TABLE "LIKE" (
   "MEMBER_NO"   NUMBER      NOT NULL,
   "BR_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "LIKE"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "LIKE"."BR_NO" IS '게시글 댓글 번호';

DROP TABLE "BOOKMARK";

CREATE TABLE "BOOKMARK" (
   "MEMBER_NO"   NUMBER      NOT NULL,
   "BOARD_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "BOOKMARK"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "BOOKMARK"."BOARD_NO" IS '게시글 번호';

DROP TABLE "AUTH_KEY";

CREATE TABLE "AUTH_KEY" (
   "MEMBER_EMAIL"   VARCHAR2(200)      NOT NULL,
   "CODE"   NUMBER      NULL
);

COMMENT ON COLUMN "AUTH_KEY"."MEMBER_EMAIL" IS '이메일';

COMMENT ON COLUMN "AUTH_KEY"."CODE" IS '코드';

DROP TABLE "ALERT";

CREATE TABLE "ALERT" (
   "ALERT_NO"   NUMBER      NOT NULL,
   "BOARD_NO"   NUMBER   DEFAULT 0   NOT NULL,
   "COMMENT_NO"   NUMBER   DEFAULT 0   NOT NULL,
   "ALERT_ST"   CHAR   DEFAULT 'N'   NULL,
   "ALERT_TARGET"   VARCHAR(255)      NULL,
   "MEMBER_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "ALERT"."ALERT_NO" IS '알림번호';

COMMENT ON COLUMN "ALERT"."BOARD_NO" IS '게시글 번호';

COMMENT ON COLUMN "ALERT"."COMMENT_NO" IS '댓글 번호';

COMMENT ON COLUMN "ALERT"."ALERT_ST" IS '읽음 Y';

COMMENT ON COLUMN "ALERT"."ALERT_TARGET" IS '목표달성';

COMMENT ON COLUMN "ALERT"."MEMBER_NO" IS '회원번호';

DROP TABLE "ACCOUNTBOOK";

CREATE TABLE "ACCOUNTBOOK" (
   "ACNT_NO"   NUMBER      NOT NULL,
   "ACNT_DATE"   VARCHAR2(100)      NOT NULL,
   "REG_DATE"   VARCHAR2(100)   DEFAULT SYSDATE   NOT NULL,
   "ACNT_CONT"   VARCHAR2(100)      NOT NULL,
   "ACNT_MN"   VARCHAR2(100)      NOT NULL,
   "MEMO"   VARCHAR2(1000)      NULL,
   "PM_MTD"   VARCHAR2(100)      NOT NULL,
   "CATE_CD"   NUMBER      NOT NULL,
   "MEMBER_NO"   NUMBER      NOT NULL,
   "ACNT_ST"   CHAR   DEFAULT 'N'   NOT NULL
);

COMMENT ON COLUMN "ACCOUNTBOOK"."ACNT_NO" IS '가계부번호';

COMMENT ON COLUMN "ACCOUNTBOOK"."ACNT_DATE" IS '해당일자';

COMMENT ON COLUMN "ACCOUNTBOOK"."REG_DATE" IS '가계부 등록일자';

COMMENT ON COLUMN "ACCOUNTBOOK"."ACNT_CONT" IS '거래처';

COMMENT ON COLUMN "ACCOUNTBOOK"."ACNT_MN" IS '금액';

COMMENT ON COLUMN "ACCOUNTBOOK"."MEMO" IS '메모';

COMMENT ON COLUMN "ACCOUNTBOOK"."PM_MTD" IS '결제수단';

COMMENT ON COLUMN "ACCOUNTBOOK"."CATE_CD" IS '카테고리코드';

COMMENT ON COLUMN "ACCOUNTBOOK"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "ACCOUNTBOOK"."ACNT_ST" IS '정상(N)/삭제(Y)';

DROP TABLE "CATEGORY";

CREATE TABLE "CATEGORY" (
   "CATE_CD"   NUMBER      NOT NULL,
   "CATE_NM"   VARCHAR2(100)      NULL,
   "INOUT_CD"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "CATEGORY"."CATE_CD" IS '카테고리코드';

COMMENT ON COLUMN "CATEGORY"."CATE_NM" IS '카테고리명';

COMMENT ON COLUMN "CATEGORY"."INOUT_CD" IS '수입/지출/이체구분코드';

DROP TABLE "INOUTTRANS";

CREATE TABLE "INOUTTRANS" (
   "INOUT_CD"   NUMBER      NOT NULL,
   "INOUT_CONT"   VARCHAR2(100)      NOT NULL
);

COMMENT ON COLUMN "INOUTTRANS"."INOUT_CD" IS '수입/지출/이체구분코드';

COMMENT ON COLUMN "INOUTTRANS"."INOUT_CONT" IS '내역분류명';

DROP TABLE "IMAGE";

CREATE TABLE "IMAGE" (
   "BR_NO"   NUMBER      NOT NULL,
   "IMG_CD"   NUMBER      NOT NULL,
   "IMG_PATH"   VARCHAR2(200)      NULL,
   "IMG_RENAME"   VARCHAR2(200)      NULL,
   "IMG_ORIGINAL"   VARCHAR2(200)      NULL,
   "IMG_LEVEL"   NUMBER      NULL
);

COMMENT ON COLUMN "IMAGE"."BR_NO" IS '게시글댓글번호';

COMMENT ON COLUMN "IMAGE"."IMG_CD" IS '분류코드';

COMMENT ON COLUMN "IMAGE"."IMG_PATH" IS '이미지경로';

COMMENT ON COLUMN "IMAGE"."IMG_RENAME" IS '이미지변경명';

COMMENT ON COLUMN "IMAGE"."IMG_ORIGINAL" IS '이미지원본명';

COMMENT ON COLUMN "IMAGE"."IMG_LEVEL" IS '썸네일0';

DROP TABLE "ACCOUNT_GROUP";

CREATE TABLE "ACCOUNT_GROUP" (
   "MEMBER_EMAIL"   VARCHAR2(50)      NOT NULL,
   "ACNT_NO"   NUMBER      NOT NULL,
   "GROUP_FL"   CHAR   DEFAULT 'N'   NOT NULL
);

COMMENT ON COLUMN "ACCOUNT_GROUP"."MEMBER_EMAIL" IS '참여 회원 이메일';

COMMENT ON COLUMN "ACCOUNT_GROUP"."ACNT_NO" IS '가계부번호';

COMMENT ON COLUMN "ACCOUNT_GROUP"."GROUP_FL" IS '참여 Y';

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
   "MEMBER_NO"
);

ALTER TABLE "SUBSCRIBE" ADD CONSTRAINT "PK_SUBSCRIBE" PRIMARY KEY (
   "SUBSCRIBE_NO"
);

ALTER TABLE "CALCULATE" ADD CONSTRAINT "PK_CALCULATE" PRIMARY KEY (
   "CALCULATE_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
   "BOARD_NO"
);

ALTER TABLE "BOARD_TYPE" ADD CONSTRAINT "PK_BOARD_TYPE" PRIMARY KEY (
   "BOARD_CODE"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "PK_COMMENT" PRIMARY KEY (
   "COMMENT_NO"
);

ALTER TABLE "CHATTING_ROOM" ADD CONSTRAINT "PK_CHATTING_ROOM" PRIMARY KEY (
   "CHATTING_NO"
);

ALTER TABLE "MESSAGE" ADD CONSTRAINT "PK_MESSAGE" PRIMARY KEY (
   "MESSAG_NO"
);

ALTER TABLE "ALERT" ADD CONSTRAINT "PK_ALERT" PRIMARY KEY (
   "ALERT_NO"
);

ALTER TABLE "ACCOUNTBOOK" ADD CONSTRAINT "PK_ACCOUNTBOOK" PRIMARY KEY (
   "ACNT_NO"
);

ALTER TABLE "CATEGORY" ADD CONSTRAINT "PK_CATEGORY" PRIMARY KEY (
   "CATE_CD"
);

ALTER TABLE "INOUTTRANS" ADD CONSTRAINT "PK_INOUTTRANS" PRIMARY KEY (
   "INOUT_CD"
);

-------------------------- 
-- 시퀀스
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE; -- 회원번호

CREATE SEQUENCE SEQ_CHATTING_NO NOCACHE; -- 채팅번호

CREATE SEQUENCE SEQ_MESSAGE_NO NOCACHE; -- 메세지번호

CREATE SEQUENCE SEQ_ALERT_NO NOCACHE; -- 알림번호

CREATE SEQUENCE SEQ_SUBSCRIBE_NO NOCACHE; -- 구독번호

CREATE SEQUENCE SEQ_CALCULATE_NO NOCACHE; -- 결제번호

CREATE SEQUENCE SEQ_ACNT_NO NOCACHE; -- 가계부번호

CREATE SEQUENCE SEQ_BOARD_NO NOCACHE; -- 게시판번호

CREATE SEQUENCE SEQ_COMMENT_NO NOCACHE; -- 댓글번호

COMMIT;


ALTER TABLE member
MODIFY MEMBER_PW VARCHAR2(1000);

UPDATE MEMBER SET MEMBER_PW = '$2a$10$.MtvvpC1JjpKcAgU2Facx.bipOcdsmlUzdBpupBppiQnaiJjm6dzy';


COMMIT;