ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

-- 계정 생성
CREATE USER final_ver1 IDENTIFIED BY "project1234";

-- 권한 부여
GRANT CONNECT, RESOURCE, CREATE VIEW TO final_ver1;

-- 객체 생성 공간 할당
ALTER USER final_ver1 DEFAULT TABLESPACE SYSTEM
QUOTA UNLIMITED ON SYSTEM;

--------------------------------------------------------------------------------

DROP TABLE "MEMBER";

CREATE TABLE "MEMBER" (
   "MEMBER_NO"   NUMBER      NOT NULL,
   "MEMBER_EMAIL"   VARCHAR2(50)      NULL,
   "MEMBER_PW"   VARCHAR2(50)      NULL,
   "MEMBER_NAME"   VARCHAR2(20)      NULL,
   "MEMBER_NICKNAME"   VARCHAR2(30)      NULL,
   "MEMBER_TEL"   VARCHAR2(30)      NULL,
   "MEMBER_ADDRESS"   VARCHAR2(100)      NULL,
   "SECESSION_FL"   CHAR   DEFAULT 'N'   NULL,
   "AUTHORITY"   NUMBER   DEFAULT 2   NULL,
   "PROFILE"   VARCHAR2(200)      NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '이메일(아이디)';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '비밀번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_NAME" IS '이름';

COMMENT ON COLUMN "MEMBER"."MEMBER_NICKNAME" IS '닉네임';

COMMENT ON COLUMN "MEMBER"."MEMBER_TEL" IS '전화번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_ADDRESS" IS '주소';

COMMENT ON COLUMN "MEMBER"."SECESSION_FL" IS '탈퇴 Y';

COMMENT ON COLUMN "MEMBER"."AUTHORITY" IS '관리자 1';

COMMENT ON COLUMN "MEMBER"."PROFILE" IS '프로필 이미지';